language: d

os:
  - linux
  - osx

dist: trusty
sudo: required

osx_image: xcode11.5

d:
  - dmd-2.092.1
  - dmd-2.082.1
  - dmd-2.068.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install llvm-3.6; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/lib/llvm-3.6/lib/libLLVM-3.6.so /usr/lib/libLLVM.so; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/lib/llvm-3.6/lib/libLTO.so /usr/lib/libLTO.so; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm@10; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force --overwrite llvm@10; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DFLAGS="-version=LLVM_3_6_0" dub run --root=examples/fibonacci --compiler=$DC --config=link-single; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then DFLAGS="-version=LLVM_10_0_0" dub run --root=examples/fibonacci --compiler=$DC --config=link-single; fi
